//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsnManagementSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coordinator()
        {
            this.Routers = new HashSet<Router>();
            this.WsnCoordinators = new HashSet<WsnCoordinator>();
        }
    
        public int CoordinatorID { get; set; }
        public string CoordinatorName { get; set; }
        public string CoordinatorDescription { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Latitude { get; set; }
        public string Longtitude { get; set; }
    
        public virtual City City { get; set; }
        public virtual County County { get; set; }
        public virtual District District { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Router> Routers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WsnCoordinator> WsnCoordinators { get; set; }
    }
}
