//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsnManagementSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Router
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Router()
        {
            this.RouterSensors = new HashSet<RouterSensor>();
            this.SensorMeasurements = new HashSet<SensorMeasurement>();
        }
    
        public int RouterID { get; set; }
        public string RouterName { get; set; }
        public string RouterDescription { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Latitude { get; set; }
        public string Longtitude { get; set; }
        public Nullable<int> CoordinatorID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Coordinator Coordinator { get; set; }
        public virtual County County { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterSensor> RouterSensors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorMeasurement> SensorMeasurements { get; set; }
    }
}
