//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsnManagementSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorMeasurement
    {
        public int SensorMeasurementID { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<int> RouterID { get; set; }
        public Nullable<int> SensorMeasurementTypeID { get; set; }
        public System.DateTime SensorMeasurementDateTime { get; set; }
        public string SensorMeasurementValue { get; set; }
    
        public virtual Router Router { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual SensorMeasurementType SensorMeasurementType { get; set; }
    }
}
