//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsnManagementSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorNetwork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SensorNetwork()
        {
            this.WsnCoordinators = new HashSet<WsnCoordinator>();
        }
    
        public int SensorNetworkID { get; set; }
        public string SensorNetworkName { get; set; }
        public string SensorNetworkDescription { get; set; }
        public Nullable<int> DomainID { get; set; }
        public Nullable<int> StatueID { get; set; }
        public System.DateTime SensorMeasurementDateTime { get; set; }
        public Nullable<int> CoordinatorID { get; set; }
    
        public virtual WsnDomain WsnDomain { get; set; }
        public virtual WsnStatu WsnStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WsnCoordinator> WsnCoordinators { get; set; }
    }
}
