//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsnManagementSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorMeasurementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SensorMeasurementType()
        {
            this.DefinationOfSensorMeasurements = new HashSet<DefinationOfSensorMeasurement>();
            this.SensorMeasurements = new HashSet<SensorMeasurement>();
        }
    
        public int SensorMeasurementTypeID { get; set; }
        public string SensorMeasurementTypeName { get; set; }
        public string SensorMeasurementTypeAbbreviation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefinationOfSensorMeasurement> DefinationOfSensorMeasurements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorMeasurement> SensorMeasurements { get; set; }
    }
}
