//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsnManagementSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WsnCoordinator
    {
        public int Id { get; set; }
        public Nullable<int> WsnSensorNetworkID { get; set; }
        public Nullable<int> CoordinatorID { get; set; }
    
        public virtual Coordinator Coordinator { get; set; }
        public virtual SensorNetwork SensorNetwork { get; set; }
    }
}
